web/router.ex
defmodule Blogie.Router do
  use Blogie.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Blogie.AuthController, repo: Blogie.Repo
  end

  pipeline :api do
    plug :accepts, ["json-api"]
    plug JaSerializer.ContentTypeNegotiation
    plug JaSerializer.Deserializer
  end

  scope "/", Blogie do
    pipe_through :browser # Use the default browser stack

    get "/", PostController, :index
    get "/posts/:id", PostController, :show
    get "/about", AboutController, :show
    resources "/session", SessionController, only: [:new, :create, :delete]
  end

  scope "/admin", Blogie.Admin, as: :admin do
    pipe_through [:browser, :authenticate_user]

    resources "/", PostController
  end

  # Other scopes may use custom stacks.
  scope "/api", Blogie.API, as: :api do
    pipe_through :api

    resources "/posts", PostController, only: [:index, :show]
  end
end

web/views/layout_view.ex
defmodule Blogie.LayoutView do
  use Blogie.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Blogie!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link href='//fonts.googleapis.com/css?family=Lusitana:400,700' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Merriweather+Sans:400,300,300italic,400italic,700italic,700,800,800italic' rel='stylesheet' type='text/css'>
  </head>

  <body>
    <main role="main" class="mainbody">
      <header class="navigation" role="banner">
        <div class="navigation-wrapper">
          <a href="<%= post_path(@conn, :index) %>" class="logo">
            <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_1.png" alt="Logo Image">
          </a>
          <a href="#" class="navigation-menu-button" id="js-mobile-menu">MENU</a>
          <nav role="navigation">
            <ul id="js-navigation-menu" class="navigation-menu show">
              <li class="nav-link"><%= link "Latest Posts", to: post_path(@conn, :index) %></li>
              <li class="nav-link"><%= link "About", to: about_path(@conn, :show) %></li>
            </ul>
          </nav>
          <div class="navigation-tools">
            <nav role="navigation">
              <ul id="js-navigation-menu" class="navigation-menu show">
                <li class="nav-link">
                  <%= if @current_user do %>
                    <%= link "All Posts", to: admin_post_path(@conn, :index), class: "link" %>
                    <%= link "New Post", to: admin_post_path(@conn, :new), class: "link" %>
                    <%= link "Logout", to: session_path(@conn, :delete, @current_user), method: "delete", class: "link" %>
                  <% else %>
                    <%=  if Application.get_env(:blogie, :dev) do %>
                      <%= link "Login", to: session_path(@conn, :new) %>
                    <%= end %>
                  <%= end %>
                </li>
              </ul>
            </nav>
          </div>
        </div>
      </header>
      <div class="outer-container">
        <%= if get_flash(@conn, :info) do %>
        <p class="alert-info" role="alert"><span ><%= get_flash(@conn, :info) %></p>
        <%= end %>
        <%= if get_flash(@conn, :error) do %>
        <p class="alert-error" role="alert"><%= get_flash(@conn, :error) %></p>
        <%= end %>


        <%= render @view_module, @view_template, assigns %>
      </div>
    </main>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>